// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article/article.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetUser
type GetCategoriesRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoriesRequest) Reset()         { *m = GetCategoriesRequest{} }
func (m *GetCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoriesRequest) ProtoMessage()    {}
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12321969c539ac1b, []int{0}
}

func (m *GetCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoriesRequest.Unmarshal(m, b)
}
func (m *GetCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoriesRequest.Marshal(b, m, deterministic)
}
func (m *GetCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoriesRequest.Merge(m, src)
}
func (m *GetCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoriesRequest.Size(m)
}
func (m *GetCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoriesRequest proto.InternalMessageInfo

func (m *GetCategoriesRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetCategoriesResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoriesResponse) Reset()         { *m = GetCategoriesResponse{} }
func (m *GetCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCategoriesResponse) ProtoMessage()    {}
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12321969c539ac1b, []int{1}
}

func (m *GetCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoriesResponse.Unmarshal(m, b)
}
func (m *GetCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoriesResponse.Marshal(b, m, deterministic)
}
func (m *GetCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoriesResponse.Merge(m, src)
}
func (m *GetCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCategoriesResponse.Size(m)
}
func (m *GetCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoriesResponse proto.InternalMessageInfo

func (m *GetCategoriesResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterType((*GetCategoriesRequest)(nil), "pb.GetCategoriesRequest")
	proto.RegisterType((*GetCategoriesResponse)(nil), "pb.GetCategoriesResponse")
}

func init() { proto.RegisterFile("article/article.proto", fileDescriptor_12321969c539ac1b) }

var fileDescriptor_12321969c539ac1b = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2c, 0x2a, 0xc9,
	0x4c, 0xce, 0x49, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x4c, 0x05, 0x49,
	0x4a, 0x1a, 0x5c, 0x22, 0xee, 0xa9, 0x25, 0xce, 0x89, 0x25, 0xa9, 0xe9, 0xf9, 0x45, 0x99, 0xa9,
	0xc5, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x02, 0x5c, 0xcc, 0xa5, 0x99, 0x29, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x92, 0x26, 0x97, 0x28, 0x9a, 0xca, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x4c, 0xa5, 0x46, 0x21, 0x5c, 0x5c, 0x8e, 0x10, 0x9b, 0x8a, 0xcb, 0x92,
	0x85, 0xdc, 0xb8, 0x78, 0x51, 0x34, 0x0a, 0x49, 0xe8, 0x15, 0x24, 0xe9, 0x61, 0xb3, 0x55, 0x4a,
	0x12, 0x8b, 0x0c, 0xc4, 0x16, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xab, 0x8d, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x4c, 0x18, 0x1f, 0xc3, 0xce, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArticlesvcClient is the client API for Articlesvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticlesvcClient interface {
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
}

type articlesvcClient struct {
	cc *grpc.ClientConn
}

func NewArticlesvcClient(cc *grpc.ClientConn) ArticlesvcClient {
	return &articlesvcClient{cc}
}

func (c *articlesvcClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, "/pb.Articlesvc/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticlesvcServer is the server API for Articlesvc service.
type ArticlesvcServer interface {
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
}

// UnimplementedArticlesvcServer can be embedded to have forward compatible implementations.
type UnimplementedArticlesvcServer struct {
}

func (*UnimplementedArticlesvcServer) GetCategories(ctx context.Context, req *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}

func RegisterArticlesvcServer(s *grpc.Server, srv ArticlesvcServer) {
	s.RegisterService(&_Articlesvc_serviceDesc, srv)
}

func _Articlesvc_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticlesvcServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Articlesvc/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticlesvcServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Articlesvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Articlesvc",
	HandlerType: (*ArticlesvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategories",
			Handler:    _Articlesvc_GetCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article/article.proto",
}
