# build debug container
# docker build -t cage1016/gokitconsul-debug-builder -f ./Dockerfile.debugbuilder .

FROM golang:1.11.5-alpine

WORKDIR /go/src/github.com/cage1016/gokitconsul

RUN apk update \
    && apk add --no-cache libc6-compat ca-certificates \
    && apk add make protobuf git musl-dev \
    && go get -u github.com/derekparker/delve/cmd/dlv