// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetUser
type GetUserRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetUserResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// Login
type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	RoleID               int32    `protobuf:"varint,4,opt,name=roleID,proto3" json:"roleID,omitempty"`
	RecentTime           string   `protobuf:"bytes,5,opt,name=recentTime,proto3" json:"recentTime,omitempty"`
	CreatedTime          string   `protobuf:"bytes,6,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          string   `protobuf:"bytes,7,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	Cookie               string   `protobuf:"bytes,8,opt,name=cookie,proto3" json:"cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *LoginResponse) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *LoginResponse) GetRecentTime() string {
	if m != nil {
		return m.RecentTime
	}
	return ""
}

func (m *LoginResponse) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *LoginResponse) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

func (m *LoginResponse) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

//SendCode
type SendCodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCodeRequest) Reset()         { *m = SendCodeRequest{} }
func (m *SendCodeRequest) String() string { return proto.CompactTextString(m) }
func (*SendCodeRequest) ProtoMessage()    {}
func (*SendCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{4}
}

func (m *SendCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCodeRequest.Unmarshal(m, b)
}
func (m *SendCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCodeRequest.Marshal(b, m, deterministic)
}
func (m *SendCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCodeRequest.Merge(m, src)
}
func (m *SendCodeRequest) XXX_Size() int {
	return xxx_messageInfo_SendCodeRequest.Size(m)
}
func (m *SendCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendCodeRequest proto.InternalMessageInfo

type SendCodeResponse struct {
	CodeID               string   `protobuf:"bytes,1,opt,name=codeID,proto3" json:"codeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCodeResponse) Reset()         { *m = SendCodeResponse{} }
func (m *SendCodeResponse) String() string { return proto.CompactTextString(m) }
func (*SendCodeResponse) ProtoMessage()    {}
func (*SendCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{5}
}

func (m *SendCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCodeResponse.Unmarshal(m, b)
}
func (m *SendCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCodeResponse.Marshal(b, m, deterministic)
}
func (m *SendCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCodeResponse.Merge(m, src)
}
func (m *SendCodeResponse) XXX_Size() int {
	return xxx_messageInfo_SendCodeResponse.Size(m)
}
func (m *SendCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendCodeResponse proto.InternalMessageInfo

func (m *SendCodeResponse) GetCodeID() string {
	if m != nil {
		return m.CodeID
	}
	return ""
}

// Register
type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CodeID               int32    `protobuf:"varint,3,opt,name=codeID,proto3" json:"codeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{6}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetCodeID() int32 {
	if m != nil {
		return m.CodeID
	}
	return 0
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{7}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

// UserList
type UserListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{8}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

func (m *UserListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserListRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type UserListResponse struct {
	Count                int64           `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data                 []*UserResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{9}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *UserListResponse) GetData() []*UserResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	RoleID               int32    `protobuf:"varint,4,opt,name=roleID,proto3" json:"roleID,omitempty"`
	RecentTime           string   `protobuf:"bytes,5,opt,name=recentTime,proto3" json:"recentTime,omitempty"`
	CreatedTime          string   `protobuf:"bytes,6,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          string   `protobuf:"bytes,7,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{10}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserResponse) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *UserResponse) GetRecentTime() string {
	if m != nil {
		return m.RecentTime
	}
	return ""
}

func (m *UserResponse) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *UserResponse) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

//Logout
type LogoutRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{11}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{12}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "pb.GetUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
	proto.RegisterType((*SendCodeRequest)(nil), "pb.SendCodeRequest")
	proto.RegisterType((*SendCodeResponse)(nil), "pb.SendCodeResponse")
	proto.RegisterType((*RegisterRequest)(nil), "pb.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "pb.RegisterResponse")
	proto.RegisterType((*UserListRequest)(nil), "pb.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "pb.UserListResponse")
	proto.RegisterType((*UserResponse)(nil), "pb.UserResponse")
	proto.RegisterType((*LogoutRequest)(nil), "pb.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "pb.LogoutResponse")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0x4d, 0x8e, 0xd4, 0x3c,
	0x10, 0x9d, 0x24, 0x9d, 0xee, 0xfe, 0x6a, 0xe6, 0xeb, 0x64, 0xcc, 0x08, 0x45, 0x59, 0xa0, 0xc6,
	0xb0, 0x18, 0xb1, 0x68, 0xc4, 0x80, 0x84, 0x58, 0x83, 0x40, 0x48, 0x23, 0x16, 0x01, 0x0e, 0xe0,
	0x8e, 0x4b, 0xad, 0x08, 0x26, 0x0e, 0xb1, 0x33, 0x48, 0xdc, 0x11, 0xae, 0xc1, 0x35, 0x90, 0xff,
	0x3a, 0x4e, 0x60, 0xc5, 0x8e, 0x4d, 0xe4, 0x7a, 0x7e, 0xaf, 0xca, 0x2e, 0xbf, 0x0a, 0x64, 0x83,
	0xc4, 0xfe, 0xb1, 0xfe, 0xec, 0xba, 0x5e, 0x28, 0x41, 0xe2, 0x6e, 0x4f, 0x29, 0x6c, 0xde, 0xa0,
	0xfa, 0x28, 0xb1, 0xaf, 0xf0, 0xcb, 0x80, 0x52, 0x91, 0x1c, 0x92, 0xa1, 0xe1, 0x45, 0xb4, 0x8d,
	0x2e, 0xff, 0xab, 0xf4, 0x92, 0x3e, 0x80, 0xec, 0xc8, 0x91, 0x9d, 0x68, 0x25, 0xfe, 0x81, 0xf4,
	0x1a, 0xce, 0xae, 0xc5, 0xa1, 0x69, 0x7d, 0x9a, 0x12, 0xd6, 0xba, 0x54, 0xcb, 0x6e, 0xd0, 0xd1,
	0x8e, 0xb1, 0xde, 0xeb, 0x98, 0x94, 0x5f, 0x45, 0xcf, 0x8b, 0xd8, 0xee, 0xf9, 0x98, 0xfe, 0x8c,
	0xe0, 0x7f, 0x97, 0xc8, 0xd5, 0xda, 0x40, 0xec, 0x4a, 0xa5, 0x55, 0xdc, 0xf0, 0x49, 0xe6, 0x78,
	0x96, 0xf9, 0x2e, 0x2c, 0xd9, 0x2d, 0x53, 0xac, 0x2f, 0x12, 0xb3, 0xe3, 0x22, 0x8d, 0xf7, 0xe2,
	0x33, 0xbe, 0x7d, 0x55, 0x2c, 0x4c, 0x1e, 0x17, 0x91, 0x7b, 0x00, 0x3d, 0xd6, 0xd8, 0xaa, 0x0f,
	0xcd, 0x0d, 0x16, 0xa9, 0xd1, 0x04, 0x08, 0xd9, 0xc2, 0x69, 0xdd, 0x23, 0x53, 0xc8, 0x0d, 0x61,
	0x69, 0x08, 0x21, 0xa4, 0x19, 0x43, 0xc7, 0x8f, 0x8c, 0x95, 0x65, 0x04, 0x90, 0xae, 0x5d, 0x0b,
	0xf1, 0xa9, 0xc1, 0x62, 0x6d, 0xcf, 0x64, 0x23, 0x7a, 0x0e, 0xd9, 0x7b, 0x6c, 0xf9, 0x4b, 0xc1,
	0xd1, 0x35, 0x8d, 0x3e, 0x82, 0x7c, 0x84, 0xdc, 0xf5, 0x8d, 0x9c, 0xeb, 0xa3, 0x47, 0x5e, 0xae,
	0x23, 0xca, 0x20, 0xab, 0xf0, 0xd0, 0x48, 0x35, 0x3e, 0xdd, 0x5f, 0xf6, 0x3c, 0x28, 0x91, 0xd8,
	0xee, 0xb8, 0x12, 0x04, 0xf2, 0xb1, 0x84, 0x3d, 0x0e, 0x7d, 0x01, 0x99, 0x76, 0xc2, 0x75, 0x23,
	0x95, 0x2f, 0x4b, 0x60, 0xd1, 0xb1, 0x03, 0xba, 0x27, 0x32, 0x6b, 0x8d, 0xc9, 0xe6, 0x9b, 0x7d,
	0xa0, 0xb4, 0x32, 0x6b, 0xfa, 0x0e, 0xf2, 0x51, 0xea, 0x6e, 0x77, 0x01, 0x69, 0x2d, 0x86, 0x56,
	0x19, 0x71, 0x52, 0xd9, 0x80, 0x3c, 0x84, 0x05, 0x67, 0x8a, 0x15, 0xf1, 0x36, 0xb9, 0x3c, 0xbd,
	0xca, 0x77, 0xdd, 0x7e, 0x17, 0xda, 0xaf, 0x32, 0xbb, 0xf4, 0x47, 0x04, 0x67, 0x13, 0x57, 0xfe,
	0xe3, 0x4e, 0xa1, 0xf7, 0x8d, 0xf5, 0xc5, 0xa0, 0x82, 0x59, 0x94, 0xe3, 0x98, 0xc9, 0x86, 0xd3,
	0x1c, 0x36, 0x9e, 0x62, 0x2f, 0x7d, 0xf5, 0x3d, 0x86, 0x95, 0xee, 0x82, 0xbc, 0xad, 0xc9, 0x33,
	0x58, 0xb9, 0x49, 0x25, 0x44, 0x37, 0x6d, 0x3a, 0xda, 0xe5, 0x9d, 0x09, 0xe6, 0x1e, 0xf4, 0x84,
	0xec, 0x20, 0x35, 0x13, 0x47, 0x4c, 0xa3, 0xc3, 0x29, 0x2e, 0xcf, 0x03, 0xe4, 0xc8, 0x7f, 0x0e,
	0x6b, 0xef, 0x52, 0x62, 0x52, 0xce, 0x6c, 0x5c, 0x5e, 0x4c, 0xc1, 0x50, 0xe8, 0xfd, 0x64, 0x85,
	0x33, 0x03, 0x5b, 0xe1, 0x6f, 0x96, 0x33, 0x42, 0xef, 0x1c, 0x2b, 0x9c, 0x59, 0xd0, 0x0a, 0xe7,
	0xe6, 0xa2, 0x27, 0xe4, 0x09, 0x2c, 0x6d, 0xbb, 0x88, 0xbf, 0xc9, 0xd8, 0xdd, 0x92, 0x84, 0x90,
	0x97, 0xec, 0x97, 0xe6, 0xe7, 0xf8, 0xf4, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xcb, 0x12,
	0x00, 0x2f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersvcClient is the client API for Usersvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersvcClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type usersvcClient struct {
	cc *grpc.ClientConn
}

func NewUsersvcClient(cc *grpc.ClientConn) UsersvcClient {
	return &usersvcClient{cc}
}

func (c *usersvcClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/pb.Usersvc/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersvcClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pb.Usersvc/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersvcClient) SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error) {
	out := new(SendCodeResponse)
	err := c.cc.Invoke(ctx, "/pb.Usersvc/SendCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersvcClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/pb.Usersvc/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersvcClient) UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/pb.Usersvc/UserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersvcClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/pb.Usersvc/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersvcServer is the server API for Usersvc service.
type UsersvcServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	SendCode(context.Context, *SendCodeRequest) (*SendCodeResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	UserList(context.Context, *UserListRequest) (*UserListResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

// UnimplementedUsersvcServer can be embedded to have forward compatible implementations.
type UnimplementedUsersvcServer struct {
}

func (*UnimplementedUsersvcServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUsersvcServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUsersvcServer) SendCode(ctx context.Context, req *SendCodeRequest) (*SendCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCode not implemented")
}
func (*UnimplementedUsersvcServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUsersvcServer) UserList(ctx context.Context, req *UserListRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (*UnimplementedUsersvcServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterUsersvcServer(s *grpc.Server, srv UsersvcServer) {
	s.RegisterService(&_Usersvc_serviceDesc, srv)
}

func _Usersvc_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersvcServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Usersvc/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersvcServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usersvc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersvcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Usersvc/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersvcServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usersvc_SendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersvcServer).SendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Usersvc/SendCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersvcServer).SendCode(ctx, req.(*SendCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usersvc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersvcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Usersvc/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersvcServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usersvc_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersvcServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Usersvc/UserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersvcServer).UserList(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usersvc_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersvcServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Usersvc/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersvcServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Usersvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Usersvc",
	HandlerType: (*UsersvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Usersvc_GetUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Usersvc_Login_Handler,
		},
		{
			MethodName: "SendCode",
			Handler:    _Usersvc_SendCode_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Usersvc_Register_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _Usersvc_UserList_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Usersvc_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
